/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#006a63',
          container: '#4fd1c5',
          fixed: '#79f7ea',
          'fixed-dim': '#5adace',
          'on-primary': '#ffffff',
          'on-container': '#005750',
          'on-fixed': '#00201d',
          'on-fixed-variant': '#00504a',
          'inverse': '#5adace',
        },
        secondary: {
          DEFAULT: '#8c4c4d',
          container: '#fdacac',
          fixed: '#ffdad9',
          'fixed-dim': '#ffb3b3',
          'on-secondary': '#ffffff',
          'on-container': '#793d3e',
        },
        tertiary: {
          DEFAULT: '#6b5f00',
          container: '#d3bf40',
          fixed: '#fae361',
          'fixed-dim': '#dcc748',
          'on-tertiary': '#ffffff',
          'on-container': '#584d00',
        },
        surface: {
          DEFAULT: '#f8f9ff',
          'off-white': '#F7FAFC',
          gray: '#EDF2F7',
          dim: '#ccdbf4',
          bright: '#f8f9ff',
          'container-lowest': '#ffffff',
          'container-low': '#eff4ff',
          'container': '#e5eeff',
          'container-high': '#dce9ff',
          'container-highest': '#d4e4fc',
          variant: '#d4e4fc',
          tint: '#006a63',
        },
        'on-surface': {
          DEFAULT: '#0d1c2e',
          variant: '#3c4947',
        },
        'on-background': '#0d1c2e',
        'inverse-surface': '#223144',
        'inverse-on-surface': '#eaf1ff',
        outline: {
          DEFAULT: '#6c7a77',
          variant: '#bbc9c7',
        },
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
          'on-error': '#ffffff',
          'on-container': '#93000a',
        },
        status: {
          pending: '#FEFCBF',
          review: '#E6FFFA',
          approved: '#C6F6D5',
          rejected: '#FED7D7',
          completed: '#BEE3F8',
          cancelled: '#E2E8F0',
        },
      },
      fontFamily: {
        montserrat: ['var(--font-montserrat)', 'sans-serif'],
        inter: ['var(--font-inter)', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.05em' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
      },
      spacing: {
        'container-max': '1280px',
        'gutter': '1.5rem',
        'margin-mobile': '1rem',
        'margin-desktop': '2rem',
        'stack-sm': '0.5rem',
        'stack-md': '1rem',
        'stack-lg': '2rem',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
      },
      boxShadow: {
        'card': '0 4px 10px rgba(0,0,0,0.04)',
        'card-hover': '0 8px 20px rgba(0,0,0,0.08)',
        'modal': '0 10px 20px rgba(0,0,0,0.08)',
        'admin-metric': '0 4px 10px rgba(0,0,0,0.02)',
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
};
