# Generated by Django 5.1.15 on 2026-07-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "Ya existe un usuario con este correo electrónico."},
                max_length=254,
                unique=True,
                verbose_name="correo electrónico",
            ),
        ),
    ]
