# Generated by Django 5.1.15 on 2026-07-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('volunteer', 'Voluntariado'), ('become_center', 'Convertirse en Centro')], max_length=20, verbose_name='tipo de solicitud')),
                ('first_name', models.CharField(max_length=100, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('state', models.CharField(blank=True, choices=[('Amazonas', 'Amazonas'), ('Anzoátegui', 'Anzoátegui'), ('Apure', 'Apure'), ('Aragua', 'Aragua'), ('Barinas', 'Barinas'), ('Bolívar', 'Bolívar'), ('Carabobo', 'Carabobo'), ('Cojedes', 'Cojedes'), ('Delta Amacuro', 'Delta Amacuro'), ('Distrito Capital', 'Distrito Capital'), ('Falcón', 'Falcón'), ('Guárico', 'Guárico'), ('Lara', 'Lara'), ('Mérida', 'Mérida'), ('Miranda', 'Miranda'), ('Monagas', 'Monagas'), ('Nueva Esparta', 'Nueva Esparta'), ('Portuguesa', 'Portuguesa'), ('Sucre', 'Sucre'), ('Táchira', 'Táchira'), ('Trujillo', 'Trujillo'), ('La Guaira', 'La Guaira'), ('Yaracuy', 'Yaracuy'), ('Zulia', 'Zulia')], max_length=100, verbose_name='estado')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_read', models.BooleanField(default=False, verbose_name='leída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'solicitud de ayuda',
                'verbose_name_plural': 'solicitudes de ayuda',
                'ordering': ['-created_at'],
            },
        ),
    ]
