# Generated by Django 5.1.15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="helprequest",
            name="center_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="nombre del centro"
            ),
        ),
    ]
