# Generated by Django 5.1.15 on 2026-07-04 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("centers", "0003_center_state_alter_center_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="center",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_centers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="creado por",
            ),
        ),
    ]
