# Generated by Django 5.1.15 on 2026-07-02 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('species', models.CharField(choices=[('dog', 'Perro'), ('cat', 'Gato'), ('other', 'Otro')], max_length=20, verbose_name='especie')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='raza')),
                ('age_months', models.PositiveIntegerField(verbose_name='edad en meses')),
                ('size', models.CharField(choices=[('small', 'Pequeño'), ('medium', 'Mediano'), ('large', 'Grande')], max_length=20, verbose_name='tamaño')),
                ('gender', models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], max_length=10, verbose_name='género')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='peso en kg')),
                ('description', models.TextField(verbose_name='descripción')),
                ('health_status', models.TextField(blank=True, verbose_name='estado de salud')),
                ('is_sterilized', models.BooleanField(default=False, verbose_name='esterilizado')),
                ('is_vaccinated', models.BooleanField(default=False, verbose_name='vacunado')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('adopted', 'Adoptada'), ('in_process', 'En Proceso de Adopción'), ('not_available', 'No Disponible')], default='available', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='centers.center', verbose_name='centro')),
            ],
            options={
                'verbose_name': 'mascota',
                'verbose_name_plural': 'mascotas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pets/images/', verbose_name='imagen')),
                ('is_primary', models.BooleanField(default=False, verbose_name='imagen principal')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pets.pet', verbose_name='mascota')),
            ],
            options={
                'verbose_name': 'imagen de mascota',
                'verbose_name_plural': 'imágenes de mascotas',
                'ordering': ['order'],
            },
        ),
    ]
