# Generated by Django 5.1.15 on 2026-07-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="is_dewormed",
            field=models.BooleanField(default=False, verbose_name="desparasitado"),
        ),
    ]
